name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Build Docker image
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file $HOME/gcp-key.json
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
          docker build --no-cache -t northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chatteroo-docker/chatapp:latest .

      - name: Push Docker image
        run: |
          docker push northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chatteroo-docker/chatapp:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatteroo \
            --image northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chatteroo-docker/chatapp:latest \
            --platform managed \
            --region northamerica-northeast1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=northamerica-northeast1" \