name: Destroy Terraform Infrastructure

on:
  workflow_dispatch: # For triggering manually

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Setup
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /home/runner/gcp-key.json
          gcloud auth activate-service-account --key-file $HOME/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region northamerica-northeast1

      - name: Initialize Terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcp-key.json
        run: |
          cd terraform
          terraform init

      - name: Destroy Terraform Infrastructure
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcp-key.json
        run: |
          cd terraform
          terraform destroy -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=northamerica-northeast1"
